init:

version: $(package_version)-{build}

clone_folder: c:\projects\jobtracker

branches:
    only:
        - master
        - beta
        - production
        - Dev

environment:
    nodejs_version: "7.4"
    GH_TOKEN:
        secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM

platform:
    - x64

install:
    - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
    - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
    - ps: $env:beta_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).beta_version
    - ps: Install-Product node $env:nodejs_version
    - npm install --global node-gyp@3.6.2
    - npm install --global windows-build-tools
    - npm install -g yarn
    - yarn
    # - npm run rebuild_sqlite3

build: off

before_test:
    - node --version
    - npm --version

test_script:
    - npm run test

after_test:
    - npm run pack

artifacts:
    - path: dist\latest.yml
      name: version file

    - path: dist\*.exe
      name: installers

deploy:
    - provider: GitHub
      tag: v$(package_version)
      release: $(package_version)
      auth_token:
          secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM
      artifact: installers, version file
      draft: true
      prerelease: false
      on:
        branch: master

    - provider: GitHub
      tag: v$(package_version)-beta$(beta_version)
      release: $(package_version)-beta$(beta_version)
      auth_token:
          secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM
      artifact: installers, version file
      draft: true
      prerelease: true
      on:
        branch: beta
