version: 0.8.{build}

init:

clone_folder: c:\projects\jobtracker

environment:
    nodejs_version: "7.4"
    GH_TOKEN:
        secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM

platform:
    - x86
    - x64

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install --global node-gyp@3.6.2
    - npm install --global windows-build-tools
    - npm install -g yarn
    - yarn
    - npm run rebuild_sqlite3

build: off

before_test:
    - node --version
    - npm --version

test_script:
    - npm test

after_test:
    - npm run pack

artifacts:
    - path: dist\latest.yml
      name: version file

    - path: dist\*.exe
      name: installers

deploy:
    - provider: github
      auth_token: $env:GH_TOKEN
      artifact:
      draft: true
      prerelease: false
      on:
        branch: master

    - provider: github
      auth_token: $env:GH_TOKEN
      artifact: /.\nupkg/
      draft: true
      prerelease: true
      on:
        branch: Dev
