version: 1.0 {build}

init:

clone_folder: c:\projects\jobtracker

environment:
    nodejs_version: "7"

platform:
    - x86
    - x64

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install
    - npm install -g windows-build-tools
    - npm run rebuild-sqlite3

build: off

before_test:
    -node --version
    -npm --version

test_script:
    -npm test

build_sucess:
    - npm run pack

artifacts:
    - path: dist\latest.yml
      name: version file

    - path: dist\*.exe
    name: installers

deploy:
    - provider: github
    auth_token:
        secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM
    artifact:
    draft: true
    prerelease: false
    on:
        branch: master

    - provider: github
    auth_token:
        secure: UgQokWY8FPEnAvHi9crKc5/WXLnYpLDB8A8xvTfAeoXMzqyyFC2meBEoKYLyalvM
    artifact: /.\nupkg/
    draft: true
    prerelease: true
    on:
        branch: Dev
